### ISSUE TITLE
Error - datashaper.workflow.workflow ERROR Error executing verb "orderby" in create_base_text_units: 'id'

### ISSUE THREAD

**Issue by tariqahsan** [microsoft/graphrag#1121]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Trying to follow steps from https://microsoft.github.io/graphrag/posts/get_started/.

Getting error - datashaper.workflow.workflow ERROR Error executing verb "orderby" in create_base_text_units: 'id'

while running the command >

python -m graphrag.index --root ./ragtest

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

```[tasklist]
### Tasks
```

**Comment by natoverse** [comment]
Can you upload your indexing-engine.log so we can inspect for errors?

**Comment by Zhujing1215** [comment]
I encountered the same problem as you。such as 09:59:06,172 datashaper.workflow.workflow ERROR Error executing verb "orderby" in create_base_text_units: 'id'
Traceback (most recent call last):
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\datashaper\engine\verbs\orderby.py", line 32, in orderby
    output = input_table.sort_values(by=columns, ascending=ascending)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\pandas\core\frame.py", line 7189, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'
09:59:06,179 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "orderby" in create_base_text_units: 'id' details=None
09:59:06,180 graphrag.index.run.run ERROR error running workflow create_base_text_units
Traceback (most recent call last):
  File "D:\zhujing\project\graphRag\graphrag\graphrag\index\run\run.py", line 225, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zhujing\project\graphRag\graphrag\graphrag\index\run\workflow.py", line 91, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\datashaper\engine\verbs\orderby.py", line 32, in orderby
    output = input_table.sort_values(by=columns, ascending=ascending)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\pandas\core\frame.py", line 7189, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZWHZ\.conda\envs\graphrag\Lib\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'.

**Comment by sakthii25** [comment]
before data pass into the create_base_text_units workflow could you please verify while loading the input as a dataframe contain all this three column text, id, title..
you can see the initial dataframe in `/graphrag/index/create_pipeline_config.py`

**Comment by tariqahsan** [comment]
Issue got resolved. Initially running - python -m graphrag.index --root ./ragtest
Logging enabled at C:\Dev\GraphRAG\ragtest\output\20240911-140326\reports\indexing-engine.log
❌ create_base_text_units
None
⠸ GraphRAG Indexer
├── Loading Input (InputFileType.text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
└── create_base_text_units
❌ Errors occurred during the pipeline run, see logs for more details. 
In the indexing-engine.log -
14:03:26,605 datashaper.workflow.workflow **ERROR Error executing verb "orderby" in create_base_text_units: 'id'**
Traceback (most recent call last):
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\datashaper\engine\verbs\orderby.py", line 32, in orderby
    output = input_table.sort_values(by=columns, ascending=ascending)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\pandas\core\frame.py", line 7189, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'
14:03:26,699 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "orderby" in create_base_text_units: 'id' details=None
14:03:26,699 graphrag.index.run.run ERROR error running workflow create_base_text_units
Traceback (most recent call last):
  File "C:\Users\TAhsan\.conda\envs\graphrag-pip\Lib\site-packages\graphrag\index\run\run.py", line 225, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\.conda\envs\graphrag-pip\Lib\site-packages\graphrag\index\run\workflow.py", line 91, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\datashaper\engine\verbs\orderby.py", line 32, in orderby
    output = input_table.sort_values(by=columns, ascending=ascending)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\pandas\core\frame.py", line 7189, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TAhsan\AppData\Roaming\Python\Python312\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'
14:03:26,699 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
14:03:26,721 graphrag.index.cli ERROR Errors occurred during the pipeline run, see logs for more details.

Cause: Had a invalid book.txt file. Probably wasn't an UTF-8 text document? I couldn't use curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt to download the book.txt file. Instead I used the URL - https://www.gutenberg.org/cache/epub/24022/pg24022.txt on a browser to display the content, copied and pasted into a local book.txt file. Might have screwed up the format some how which apparently wasn't visible.

Solution: Got the valid book.txt and the indexing command - python -m graphrag.index --root ./ragtest
ran successfully -
⠋ GraphRAG Indexer
├── Loading Input (InputFileType.text) - 2 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
├── create_final_entities
├── create_final_nodes
├── create_final_communities
├── join_text_units_to_entity_ids
├── create_final_relationships
├── join_text_units_to_relationship_ids
├── create_final_community_reports
├── create_final_text_units
├── create_base_documents
└── create_final_documents
🚀 All workflows completed successfully.

Was able to do the query - python -m graphrag.query --root ./ragtest --method local "Who is Scrooge, and what are his main relationships?"
INFO: Vector Store Args: {}
[2024-09-11T21:11:29Z WARN  lance::dataset] No existing dataset at C:\Dev\GraphRAG\ragtest\output\20240911-164219\artifacts\lancedb\entity_description_embeddings.lance, it will be created
...
SUCCESS: Local Search Response:
## Who is Scrooge?
 
Ebenezer Scrooge is the central character in Charles Dickens' "A Christmas Carol." He is depicted as a miserly old businessman, characterized by his cold demeanor and profound disdain for Christmas and human connection. Initially, Scrooge is indifferent to the struggles of the poor and dismissive of the holiday's associated cheer. His transformation begins when he is confronted by the ghost of his former business partner, Jacob Marley, who warns him about the consequences of his life choices and the need for change.
...
Thank you all for your suggestions.

**Comment by meoow113** [comment]
i hava same problem, how do you solve it??

**Comment by Zhujing1215** [comment]
> 我有同样的问题，你是如何解决的？

Check each of your configuration items carefully. Just follow the documentation step by step. I was careless and filled in the wrong things.
