### ISSUE TITLE
How to obtain corresponding articles？

### ISSUE THREAD

**Issue by minglong-huang** [microsoft/graphrag#1210]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

How can I know how many articles the system has retrieved and what they are when I run Query? And retrieve the paragraphs related to the answers to the questions found in these articles
当我运行 Query 时，我如何能知道系统检索到了多少篇文章，这些文章分别是什么？并获取检索到这些文章与问题答案相关的段落
谢谢大家

```[tasklist]
### Tasks
```
