### ISSUE TITLE
[Feature Request]: <title> Utilize multiple columns in csv file/Add meta information to each row manually

### ISSUE THREAD

**Issue by YepJin** [microsoft/graphrag#1290]
### Do you need to file an issue?

- [x] I have searched the existing issues and this feature is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

Hi, 
It is simialr to these two issues but not exactly the same.
https://github.com/microsoft/graphrag/issues/1194
https://github.com/microsoft/graphrag/issues/1025

Mainly I have a csv file with multiple columns, for example, a book.csv shown below. While i can have graphrag to process the "story" column to find relationship among these entities, I also want to have meta data incorporated into the graph. For example, the "Country" column so that I can easily track what are some main characteristics described in western countried or eastern countries. I think it also helps in the medical report where some meta information (producer, year) is exclusively recorded. 

![Image](https://github.com/user-attachments/assets/ac630f80-2999-4902-8052-5eb584f78ed2)

### Describe the solution you'd like

I expected two solutions. 

- Mainly, I hope there is a easy way to add nodes/relationship from the input. In the above book.csv example, ideally there should be a "Story" node where all the entities/relationship extracted in "Story" column is connected to this node. And It should be connected to the country and writer node which can be found on csv file.
- If possible, easy to process multiple columns as meta data.

### Additional context

Thanks for your time!

**Comment by natoverse** [comment]
We have the ability to specify metadata columns to include in each text chunk ([see here](https://microsoft.github.io/graphrag/index/inputs/)). You could use this to do your own filtering (either by manual processing or vector search). However, we don't have any plans to add richer graph navigation/linking/filtering.
